// Generated by gencpp from file fov/CheckRequest.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_CHECKREQUEST_H
#define FOV_MESSAGE_CHECKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fov
{
template <class ContainerAllocator>
struct CheckRequest_
{
  typedef CheckRequest_<ContainerAllocator> Type;

  CheckRequest_()
    : data(0)  {
    }
  CheckRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::fov::CheckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fov::CheckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckRequest_

typedef ::fov::CheckRequest_<std::allocator<void> > CheckRequest;

typedef boost::shared_ptr< ::fov::CheckRequest > CheckRequestPtr;
typedef boost::shared_ptr< ::fov::CheckRequest const> CheckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fov::CheckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fov::CheckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fov::CheckRequest_<ContainerAllocator1> & lhs, const ::fov::CheckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fov::CheckRequest_<ContainerAllocator1> & lhs, const ::fov::CheckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fov::CheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fov::CheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CheckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fov::CheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::fov::CheckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::fov::CheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fov/CheckRequest";
  }

  static const char* value(const ::fov::CheckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fov::CheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
;
  }

  static const char* value(const ::fov::CheckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fov::CheckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fov::CheckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fov::CheckRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOV_MESSAGE_CHECKREQUEST_H
