// Generated by gencpp from file fov/Check.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_CHECK_H
#define FOV_MESSAGE_CHECK_H

#include <ros/service_traits.h>


#include <fov/CheckRequest.h>
#include <fov/CheckResponse.h>


namespace fov
{

struct Check
{

typedef CheckRequest Request;
typedef CheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Check
} // namespace fov


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fov::Check > {
  static const char* value()
  {
    return "f8c2075a484d0d4e2762c28ac0073c54";
  }

  static const char* value(const ::fov::Check&) { return value(); }
};

template<>
struct DataType< ::fov::Check > {
  static const char* value()
  {
    return "fov/Check";
  }

  static const char* value(const ::fov::Check&) { return value(); }
};


// service_traits::MD5Sum< ::fov::CheckRequest> should match
// service_traits::MD5Sum< ::fov::Check >
template<>
struct MD5Sum< ::fov::CheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fov::Check >::value();
  }
  static const char* value(const ::fov::CheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fov::CheckRequest> should match
// service_traits::DataType< ::fov::Check >
template<>
struct DataType< ::fov::CheckRequest>
{
  static const char* value()
  {
    return DataType< ::fov::Check >::value();
  }
  static const char* value(const ::fov::CheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fov::CheckResponse> should match
// service_traits::MD5Sum< ::fov::Check >
template<>
struct MD5Sum< ::fov::CheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fov::Check >::value();
  }
  static const char* value(const ::fov::CheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fov::CheckResponse> should match
// service_traits::DataType< ::fov::Check >
template<>
struct DataType< ::fov::CheckResponse>
{
  static const char* value()
  {
    return DataType< ::fov::Check >::value();
  }
  static const char* value(const ::fov::CheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOV_MESSAGE_CHECK_H
