// Generated by gencpp from file fov/CoordinateRequest.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_COORDINATEREQUEST_H
#define FOV_MESSAGE_COORDINATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt8MultiArray.h>

namespace fov
{
template <class ContainerAllocator>
struct CoordinateRequest_
{
  typedef CoordinateRequest_<ContainerAllocator> Type;

  CoordinateRequest_()
    : idx(0)
    , xmin(0)
    , xmax(0)
    , ymin(0)
    , ymax(0)
    , mask()  {
    }
  CoordinateRequest_(const ContainerAllocator& _alloc)
    : idx(0)
    , xmin(0)
    , xmax(0)
    , ymin(0)
    , ymax(0)
    , mask(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _idx_type;
  _idx_type idx;

   typedef int32_t _xmin_type;
  _xmin_type xmin;

   typedef int32_t _xmax_type;
  _xmax_type xmax;

   typedef int32_t _ymin_type;
  _ymin_type ymin;

   typedef int32_t _ymax_type;
  _ymax_type ymax;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _mask_type;
  _mask_type mask;





  typedef boost::shared_ptr< ::fov::CoordinateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fov::CoordinateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinateRequest_

typedef ::fov::CoordinateRequest_<std::allocator<void> > CoordinateRequest;

typedef boost::shared_ptr< ::fov::CoordinateRequest > CoordinateRequestPtr;
typedef boost::shared_ptr< ::fov::CoordinateRequest const> CoordinateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fov::CoordinateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fov::CoordinateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fov::CoordinateRequest_<ContainerAllocator1> & lhs, const ::fov::CoordinateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx &&
    lhs.xmin == rhs.xmin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymin == rhs.ymin &&
    lhs.ymax == rhs.ymax &&
    lhs.mask == rhs.mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fov::CoordinateRequest_<ContainerAllocator1> & lhs, const ::fov::CoordinateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fov::CoordinateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fov::CoordinateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CoordinateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CoordinateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CoordinateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CoordinateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fov::CoordinateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59330ecd12d514a4552b7f072136e8ea";
  }

  static const char* value(const ::fov::CoordinateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59330ecd12d514a4ULL;
  static const uint64_t static_value2 = 0x552b7f072136e8eaULL;
};

template<class ContainerAllocator>
struct DataType< ::fov::CoordinateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fov/CoordinateRequest";
  }

  static const char* value(const ::fov::CoordinateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fov::CoordinateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 idx\n"
"int32 xmin\n"
"int32 xmax\n"
"int32 ymin\n"
"int32 ymax\n"
"std_msgs/UInt8MultiArray mask\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::fov::CoordinateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fov::CoordinateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
      stream.next(m.xmin);
      stream.next(m.xmax);
      stream.next(m.ymin);
      stream.next(m.ymax);
      stream.next(m.mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fov::CoordinateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fov::CoordinateRequest_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<int8_t>::stream(s, indent + "  ", v.idx);
    s << indent << "xmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "xmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "ymax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "mask: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOV_MESSAGE_COORDINATEREQUEST_H
