// Generated by gencpp from file fov/CoordinateResponse.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_COORDINATERESPONSE_H
#define FOV_MESSAGE_COORDINATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fov
{
template <class ContainerAllocator>
struct CoordinateResponse_
{
  typedef CoordinateResponse_<ContainerAllocator> Type;

  CoordinateResponse_()
    {
    }
  CoordinateResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fov::CoordinateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fov::CoordinateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinateResponse_

typedef ::fov::CoordinateResponse_<std::allocator<void> > CoordinateResponse;

typedef boost::shared_ptr< ::fov::CoordinateResponse > CoordinateResponsePtr;
typedef boost::shared_ptr< ::fov::CoordinateResponse const> CoordinateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fov::CoordinateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fov::CoordinateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fov::CoordinateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fov::CoordinateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CoordinateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::CoordinateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CoordinateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::CoordinateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fov::CoordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fov::CoordinateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fov::CoordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fov/CoordinateResponse";
  }

  static const char* value(const ::fov::CoordinateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fov::CoordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::fov::CoordinateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fov::CoordinateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fov::CoordinateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fov::CoordinateResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FOV_MESSAGE_COORDINATERESPONSE_H
