// Generated by gencpp from file fov/FishState.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_FISHSTATE_H
#define FOV_MESSAGE_FISHSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fov
{
template <class ContainerAllocator>
struct FishState_
{
  typedef FishState_<ContainerAllocator> Type;

  FishState_()
    : direction(0)
    , x(0)
    , y(0)  {
    }
  FishState_(const ContainerAllocator& _alloc)
    : direction(0)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _direction_type;
  _direction_type direction;

   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::fov::FishState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fov::FishState_<ContainerAllocator> const> ConstPtr;

}; // struct FishState_

typedef ::fov::FishState_<std::allocator<void> > FishState;

typedef boost::shared_ptr< ::fov::FishState > FishStatePtr;
typedef boost::shared_ptr< ::fov::FishState const> FishStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fov::FishState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fov::FishState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fov::FishState_<ContainerAllocator1> & lhs, const ::fov::FishState_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fov::FishState_<ContainerAllocator1> & lhs, const ::fov::FishState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fov::FishState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fov::FishState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::FishState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::FishState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::FishState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::FishState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fov::FishState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "113921524c1e6a5b46daec728ccb3e30";
  }

  static const char* value(const ::fov::FishState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x113921524c1e6a5bULL;
  static const uint64_t static_value2 = 0x46daec728ccb3e30ULL;
};

template<class ContainerAllocator>
struct DataType< ::fov::FishState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fov/FishState";
  }

  static const char* value(const ::fov::FishState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fov::FishState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FishState.msg\n"
"uint16 direction\n"
"uint16 x\n"
"uint16 y\n"
;
  }

  static const char* value(const ::fov::FishState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fov::FishState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FishState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fov::FishState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fov::FishState_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.direction);
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOV_MESSAGE_FISHSTATE_H
