// Generated by gencpp from file fov/Light.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_LIGHT_H
#define FOV_MESSAGE_LIGHT_H

#include <ros/service_traits.h>


#include <fov/LightRequest.h>
#include <fov/LightResponse.h>


namespace fov
{

struct Light
{

typedef LightRequest Request;
typedef LightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Light
} // namespace fov


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fov::Light > {
  static const char* value()
  {
    return "b21ecd0878e18358dcca817a8b8fc556";
  }

  static const char* value(const ::fov::Light&) { return value(); }
};

template<>
struct DataType< ::fov::Light > {
  static const char* value()
  {
    return "fov/Light";
  }

  static const char* value(const ::fov::Light&) { return value(); }
};


// service_traits::MD5Sum< ::fov::LightRequest> should match
// service_traits::MD5Sum< ::fov::Light >
template<>
struct MD5Sum< ::fov::LightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fov::Light >::value();
  }
  static const char* value(const ::fov::LightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fov::LightRequest> should match
// service_traits::DataType< ::fov::Light >
template<>
struct DataType< ::fov::LightRequest>
{
  static const char* value()
  {
    return DataType< ::fov::Light >::value();
  }
  static const char* value(const ::fov::LightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fov::LightResponse> should match
// service_traits::MD5Sum< ::fov::Light >
template<>
struct MD5Sum< ::fov::LightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fov::Light >::value();
  }
  static const char* value(const ::fov::LightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fov::LightResponse> should match
// service_traits::DataType< ::fov::Light >
template<>
struct DataType< ::fov::LightResponse>
{
  static const char* value()
  {
    return DataType< ::fov::Light >::value();
  }
  static const char* value(const ::fov::LightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOV_MESSAGE_LIGHT_H
