// Generated by gencpp from file fov/LightRequest.msg
// DO NOT EDIT!


#ifndef FOV_MESSAGE_LIGHTREQUEST_H
#define FOV_MESSAGE_LIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fov
{
template <class ContainerAllocator>
struct LightRequest_
{
  typedef LightRequest_<ContainerAllocator> Type;

  LightRequest_()
    : data(0.0)  {
    }
  LightRequest_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::fov::LightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fov::LightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LightRequest_

typedef ::fov::LightRequest_<std::allocator<void> > LightRequest;

typedef boost::shared_ptr< ::fov::LightRequest > LightRequestPtr;
typedef boost::shared_ptr< ::fov::LightRequest const> LightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fov::LightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fov::LightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fov::LightRequest_<ContainerAllocator1> & lhs, const ::fov::LightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fov::LightRequest_<ContainerAllocator1> & lhs, const ::fov::LightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fov::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fov::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fov::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::LightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fov::LightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fov::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73fcbf46b49191e672908e50842a83d4";
  }

  static const char* value(const ::fov::LightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73fcbf46b49191e6ULL;
  static const uint64_t static_value2 = 0x72908e50842a83d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::fov::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fov/LightRequest";
  }

  static const char* value(const ::fov::LightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fov::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n"
;
  }

  static const char* value(const ::fov::LightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fov::LightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fov::LightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fov::LightRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOV_MESSAGE_LIGHTREQUEST_H
