(cl:defpackage fov-srv
  (:use )
  (:export
   "CHECK"
   "<CHECK-REQUEST>"
   "CHECK-REQUEST"
   "<CHECK-RESPONSE>"
   "CHECK-RESPONSE"
   "COORDINATE"
   "<COORDINATE-REQUEST>"
   "COORDINATE-REQUEST"
   "<COORDINATE-RESPONSE>"
   "COORDINATE-RESPONSE"
   "EPDIMAGE"
   "<EPDIMAGE-REQUEST>"
   "EPDIMAGE-REQUEST"
   "<EPDIMAGE-RESPONSE>"
   "EPDIMAGE-RESPONSE"
   "LIGHT"
   "<LIGHT-REQUEST>"
   "LIGHT-REQUEST"
   "<LIGHT-RESPONSE>"
   "LIGHT-RESPONSE"
  ))

